# Use root/example as user/password credentials
version: '3.1'

services:
  #Nginx Service
  nginx:
    build:
      context: .
      dockerfile: docker/nginx.docker
    volumes:
      - ./:/var/www
      - ./docker/nginx/ssl:/etc/nginx/ssl
    ports:
      - "8088:443"
    links:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    links:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - "./docker/mysql:/var/lib/mysql"
    ports:
      - "33063:3306"

  node:
    build:
      context: .
      dockerfile: docker/node/node.docker
    container_name: node
    volumes:
      - ./:/var/www
    tty: true
